# Generated by Django 3.0.8 on 2021-01-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='ppub_date',
            new_name='bpub_date',
        ),
    ]
