# Generated by Django 3.0.8 on 2021-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_heroinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(verbose_name='发布日期'),
        ),
    ]
